### ISSUE TITLE
Possibly incorrect register response signature validation

### ISSUE THREAD

**Issue by mastahyeti** [castle/ruby-u2f#11]
This library uses the SHA256 digest of the `client_data` JSON string as the third field in the signing payload [here](https://github.com/castle/ruby-u2f/blob/master/lib/u2f/register_response.rb#L93):

```ruby
    def verify(app_id)
      # Chapter 4.3 in
      # http://fidoalliance.org/specs/fido-u2f-raw-message-formats-v1.0-rd-20141008.pdf
      data = [
        "\x00",
        Digest::SHA256.digest(app_id),
        Digest::SHA256.digest(client_data_json),
        key_handle_raw,
        public_key_raw
      ].join

      parsed_certificate.public_key.verify(OpenSSL::Digest::SHA256.new, signature, data)
    end
```

According to section 4.3 of the raw message format spec, the third field is supposed to be the "challenge parameter". I'm just wondering if this is an error in the spec or in the code here. The code seems to work, so I'm assuming it's an error in the spec. Also, let me know if I'm reading the spec wrong. Thanks.

**Comment by wallin** [comment]
The spec isn't all that clear, but In 4.1, it says "The challenge parameter is the SHA-256 hash of the Client Data, a stringified JSON data structure that the FIDO Client prepares".
We could add a note about that for clarity.

**Comment by mastahyeti** [comment]
Doh, that's a pretty terribly named field, given that there is also the `challenge` generated by the server. Thanks for clarifying that for me.
