### ISSUE TITLE
Tested with Plug-Up U2F dongle?

### ISSUE THREAD

**Issue by tilllt** [castle/ruby-u2f#15]
Hi, i gave this a shot, installed the fido u2f extension on chrome and tried the ruby-u2f sample app. while the key (plug-up u2f dongle) seems to register fine, the verification step returns "Unknown error, try again"... 

does the sample app really work with all u2f keys or just yubicos?

**Comment by wallin** [comment]
Hey, thanks for reporting. I have only tried with the Yubico Nano, and the lib is implemented after Yubicos ref-code.

I guess it works with eg. gmail for you? I updated the example to use the latest (0.2.0) gem, could you try again?

**Comment by tilllt** [comment]
YES! that did it, thanks a bunch. and now hope u2f gets implemented natively in some browsers ;)

**Comment by wallin** [comment]
Yes, exactly :)
Perfect! I'll close this then
