### ISSUE TITLE
Release 1.0.0 to RubyGems

### ISSUE THREAD

**Issue by bdewater** [castle/ruby-u2f#28]
https://rubygems.org/gems/u2f shows 0.2.1 while https://github.com/castle/ruby-u2f/releases/tag/1.0.0 is tagged, but without bumping `U2F::VERSION`. Is there a reason not to use 1.0.0 right now for this new project I'm working on?

**Comment by wallin** [comment]
@bdewater Thank for reporting! I've now bumped the version and released 1.0.0

**Comment by bdewater** [comment]
Thanks @wallin!
