### ISSUE TITLE
Example Outdated

### ISSUE THREAD

**Issue by hadmut** [castle/ruby-u2f#31]
The Repo contains the source for version 1.0.0 of the u2f gem, but the example still uses 0.2.0 in the Gemfile.lock (which, btw., does not compile with a recent linux (compile errors). 

The example should meet the version of the library (without the need to upgrade it).

**Comment by drewsamsen** [comment]
@hadmut can you point me to an up-to-date example? See the problem I'm having in https://github.com/castle/ruby-u2f/issues/34

**Comment by mensfeld** [comment]
Fixes are in place (based on the PR merged) so closing this.
